workflows:
  ios-build:
    name: ARKitRobotApp iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build archive
        script: |
          # Build the executable
          xcodebuild archive \
            -scheme "ARKitRobotApp" \
            -archivePath "$CM_BUILD_DIR/ARKitRobotApp.xcarchive" \
            -destination "generic/platform=iOS"

      - name: Construct Manual .ipa
        script: |
          # Define paths
          IPA_DIR="$CM_BUILD_DIR/build/ios/ipa"
          PAYLOAD_DIR="$IPA_DIR/Payload"
          APP_BUNDLE="$PAYLOAD_DIR/ARKitRobotApp.app"
          
          # 1. Find the binary file inside the archive
          # It might be in usr/local/bin because it's an executable
          BINARY_SOURCE=$(find "$CM_BUILD_DIR/ARKitRobotApp.xcarchive" -name "ARKitRobotApp" -type f | head -n 1)
          
          if [ -z "$BINARY_SOURCE" ]; then
            echo "Error: Could not find the compiled binary!"
            exit 1
          fi
          
          echo "Found binary at: $BINARY_SOURCE"

          # 2. Create the Payload and .app folder structure manually
          mkdir -p "$APP_BUNDLE"
          
          # 3. Move the binary into the .app folder
          cp "$BINARY_SOURCE" "$APP_BUNDLE/ARKitRobotApp"
          
          # 4. Copy the Info.plist into the .app folder
          # We assume Info.plist is in the root directory
          cp "$CM_BUILD_DIR/Info.plist" "$APP_BUNDLE/Info.plist"
          
          # 5. Zip it into an .ipa
          cd "$IPA_DIR"
          zip -r "ARKitRobotApp.ipa" "Payload"
            
    artifacts:
      - build/ios/ipa/*.ipa